// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.0.1',
    date: '2026-08-04',
    content: {
      en: `- Migrate JetBrains CC GUI to VS Code`,
      zh: `- 迁移 JetBrains CC GUI 到 VSCode`,
    },
  },
];
