// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.1.8',
    date: '2026-08-27',
    content: {
      en: `✨ Features
- Add a **Claude plan-usage bar** in the input toolbar, colored by spend pace vs. the 5h / 7d window budget, with a worst-window warning dot; **z.ai / GLM** backends fill the same bar from the monitor quota endpoint (plan tier, stale-cache hint) instead of SDK \`rate_limit_event\`
- Nest **model / effort / speed / 1M context** into a compact model-config dropdown with in-viewport fly-outs and delayed submenu hover, so the input toolbar stays readable in narrow panel widths

🔧 Improvements
- Switch Claude settings startup sync to **repair-only fill-in-the-blanks**: missing provider-managed fields are added, existing user values (including per-env keys) in \`~/.claude/settings.json\` are never overwritten
- Signal daemon **ready before SDK preload** so extension startup / heartbeats are no longer blocked on the Claude Agent SDK import

🐛 Fixes
- Clear **model-routing env vars** (\`ANTHROPIC_MODEL\` / \`ANTHROPIC_DEFAULT_*\`) in the settings override so \`~/.claude/settings.json\` can no longer pin every model family to one model (#1509)
- Preserve **Claude thinking-block boundaries** during streaming so independent thoughts are no longer concatenated across assistant messages
- Fix **\`@file\` references with spaces in the filename** on both the input and the rendered message, and preserve ordinary text between consecutive file chips (#1726)
- Preserve **existing input content** when inserting an editor selection / snippet while a stale webview selection is still non-collapsed (#1700)
- Stop **MCP stdio container leaks** by closing stdin (EOF) before signalling, and expand \`\${VAR}\` placeholders in \`.mcp.json\` env from Claude settings files (#1721, #1722)
- Migrate the retired **Commit AI / Prompt Enhancer** default \`claude-sonnet-4-6\` to \`claude-sonnet-5\` on read (#1693)
- Isolate **model labels and icons by provider** so third-party catalogs whose ids collide with \`claude-*\` slots no longer inherit Claude mappings
- Restore **Codex subagent lifecycle and plan rendering**: isolate \`update_plan\` to the current turn, hide opaque spawn prompts, ignore late status responses from other sessions, and keep transient status failures retryable
- Restore **Codex 0.148+ rollout history** by indexing sessions whose user prompt is a \`response_item\`
- Migrate the retired **\`claude-sonnet-4-7\` default to \`claude-sonnet-5\`**; saved retired model ids now self-heal to live models on restore instead of pinning a dead model (#1678)`,
      zh: `✨ 新功能
- 输入栏工具区新增 **Claude 套餐用量条**：按 5h / 7d 窗口的消耗节奏着色，并用最差窗口圆点提示风险；**z.ai / GLM** 后端改为从 monitor 配额接口填充同一条用量条（展示套餐档位、过期缓存提示），而不再依赖 SDK \`rate_limit_event\`
- 将 **模型 / 推理强度 / 速度 / 1M 上下文** 收进紧凑的模型配置下拉，子菜单限制在视口内弹出并延迟 hover 切换，窄宽度下输入工具栏仍可读

🔧 优化
- Claude 设置启动同步改为 **只补缺失字段**：仅填充缺失的供应商管理字段，永不覆盖用户在 \`~/.claude/settings.json\` 中的已有值（含 env 里的单个键）
- Daemon 在 SDK 预加载前先发 **ready**，扩展启动 / 心跳不再被 Claude Agent SDK 导入阻塞

🐛 修复
- 在 settings override 中清空 **模型路由环境变量**（\`ANTHROPIC_MODEL\` / \`ANTHROPIC_DEFAULT_*\`），避免 \`~/.claude/settings.json\` 把所有模型族钉到同一个模型（#1509）
- 流式输出中保留 **Claude thinking 块边界**，独立思考内容不再被拼接到一起
- 修复 **文件名含空格的 \`@file\` 引用** 在输入框与消息展示两侧被截断的问题，并保留连续文件 chip 之间的普通文本（#1726）
- 在 webview 仍残留未折叠选区时插入编辑器选区 / 片段，**不再删掉输入框已有内容**（#1700）
- 先关闭 stdin（EOF）再发信号，避免 **MCP stdio 容器泄漏**；并从 Claude settings 文件展开 \`.mcp.json\` env 中的 \`\${VAR}\` 占位符（#1721、#1722）
- 读取时把已退役的 **Commit AI / Prompt Enhancer** 默认模型 \`claude-sonnet-4-6\` 迁移为 \`claude-sonnet-5\`（#1693）
- **按 provider 隔离模型标签与图标**，第三方目录里与 \`claude-*\` 槽位撞 id 的条目不再套用 Claude 映射
- 修复 **Codex 子代理生命周期与计划渲染**：将 \`update_plan\` 隔离到当前轮，隐藏不透明的 spawn prompt，忽略来自其他会话的迟到状态响应，瞬时状态失败保持可重试
- 恢复 **Codex 0.148+ rollout 历史**：索引 user prompt 为 \`response_item\` 的会话
- 已退役的 **\`claude-sonnet-4-7\` 默认模型迁移为 \`claude-sonnet-5\`**；恢复的退役模型 id 自动自愈为在役模型，不再钉在失效模型上（#1678）`,
    },
  },
  {
    version: '0.1.7',
    date: '2026-08-23',
    content: {
      en: `- Add DeepSeek Harness (DSH) provider: persistent daemon-hosted sessions with preset overlays, approval bridging, and full history
- Add OMP CLI provider with dedicated session/service layer and history reader
- Migrate Grok to a persistent ACP service for more stable long-running sessions
- Claude: conversation chain, message rewind, and task completion notifications
- Codex: plan parsing, plan usage tracking, and enhanced MCP admin
- Webview: subagent status panel upgrades, richer message rendering, and chat input enhancements`,
      zh: `- 新增 DeepSeek Harness（DSH）Provider：常驻守护进程承载会话，支持预设覆盖、审批桥接与完整历史
- 新增 OMP CLI Provider：独立会话/服务层与历史读取
- Grok 迁移至常驻 ACP 服务，长会话更稳定
- Claude：会话链、消息回溯（rewind）与任务完成通知
- Codex：计划解析、计划用量统计与 MCP 管理增强
- Webview：子代理状态面板升级、消息渲染增强与输入框改进`,
    },
  },
  {
    version: '0.1.5',
    date: '2026-08-19',
    content: {
      en: `- Bump version to 0.1.5
- Fix auto-open-file: closing the setting no longer keeps auto-selecting ContextBar files
- Inject active file path into CLI providers (OpenCode / Grok / Kimi / Pi) so path questions work
- Use ContextBar chip path as send fallback when active editor is unavailable
- Track async subagents, sidechain edits, and multi-window permissions more reliably
- Allow collapsing thinking blocks during conversation
- Stop title-generation logs from leaking into chat; improve DeepSeek UX`,
      zh: `- 版本升级到 0.1.5
- 修复关闭「发送打开的文件路径」后 ContextBar 仍自动选中文件
- CLI Provider（OpenCode / Grok / Kimi / Pi）发送时注入当前活动文件路径
- ContextBar 芯片路径作为发送回退，避免 webview 焦点丢失编辑器上下文
- 异步子代理跟踪、侧链编辑与多窗口权限稳定性改进
- 允许对话中折叠 thinking 块
- 修复标题生成日志泄漏到聊天；优化 DeepSeek UX`,
    },
  },
  {
    version: '0.1.3',
    date: '2026-08-12',
    content: {
      en: `- Bump version to 0.1.3
- Wire task completion notification setting and show an in-panel toast when a turn finishes
- Make Stop kill Grok/Kimi/OpenCode/Pi CLI children; suppress toast/sound after user abort
- Treat Codex Aborted as a quiet interrupt instead of a chat ERROR bubble
- Fix intermittent leftover chat after "new session" (cancel deferred updateMessages, hard clear, remount list)
- Open new chat panels as stacked editor tabs in the same group instead of side-by-side splits`,
      zh: `- 版本升级到 0.1.3
- 打通任务完成通知设置：回合结束时显示面板内 toast
- Stop 可可靠终止 Grok/Kimi/OpenCode/Pi 子进程；用户主动中止后抑制完成 toast/音效
- Codex 中断按安静处理，不再弹出 ERROR 气泡
- 修复偶现「新会话仍显示旧对话」（取消延迟消息回写、强制清空、重挂载列表）
- 新页签改为同一编辑器组叠开，不再左右分屏`,
    },
  },
  {
    version: '0.1.2',
    date: '2026-08-11',
    content: {
      en: `- Bump version to 0.1.2
- Fix Grok history: restore attached images when reloading sessions
- Fix Grok session titles: prefer typed user_query over English AI generated_title (including image turns)
- Fix Grok image send: pass attachments via \`--prompt-file\` so the model can see images (UI no longer shows a false optimistic-only image)
- Fix tool spinners stuck pending after multi-step agent turns / stream end`,
      zh: `- 版本升级到 0.1.2
- 修复 Grok 历史重载后用户附件图片丢失
- 修复 Grok 会话标题：优先使用用户输入原文，不再误用英文 AI 标题（含带图消息）
- 修复 Grok 发图：通过 \`--prompt-file\` 把附件真正传给模型（避免仅 UI 有图、模型看不到）
- 修复多步工具调用结束后转圈不消失的问题`,
    },
  },
  {
    version: '0.1.1',
    date: '2026-08-10',
    content: {
      en: `- Bump version to 0.1.1
- Fix chat toolbar selectors clipped by overflow (config / provider / mode unclickable)
- Fix revoking local settings.json authorization
- Surface Codex/Claude send failures in chat; swallow success JSON envelopes
- Fix Grok/CLI history isolation`,
      zh: `- 版本升级到 0.1.1
- 修复底部工具栏配置/供应商/模式按钮菜单被裁切导致点不动
- 修复取消本地 settings.json 授权无效
- 发送失败在聊天区展示；成功结果 JSON 不再误入正文
- 修复 Grok/CLI 历史隔离`,
    },
  },
  {
    version: '0.1.0',
    date: '2026-08-10',
    content: {
      en: `- Bump version to 0.1.0 for Marketplace-compatible SemVer
- Clean packaging ignores (drop tests, sql.js debug builds, non-dist webview files)
- Remove personal local paths from README packaging instructions`,
      zh: `- 版本升级到 0.1.0，符合 Marketplace 的 SemVer 要求
- 收紧打包忽略规则（排除测试、sql.js debug 构建、非 dist 的 webview 文件）
- 移除 README 打包说明中的个人本机路径`,
    },
  },
  {
    version: '0.0.2-fix2',
    date: '2026-08-05',
    content: {
      en: `- Add \`enableDebugLog\` setting (default off) and show Webview DevTools only when enabled
- Fix chat input drag-and-drop for files from Explorer (path references and images)
- Improve dependency detection and permission approvals`,
      zh: `- 新增「调试日志」开关（默认关闭），仅开启时显示 Webview 开发者工具按钮
- 修复输入框拖放：支持从资源管理器拖入文件路径引用与图片
- 改进依赖检测与权限审批`,
    },
  },
  {
    version: '0.0.1',
    date: '2026-08-04',
    content: {
      en: `- Migrate JetBrains CC GUI to VS Code`,
      zh: `- 迁移 JetBrains CC GUI 到 VSCode`,
    },
  },
];
