// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.0.2-fix2',
    date: '2026-08-05',
    content: {
      en: `- Add \`enableDebugLog\` setting (default off) and show Webview DevTools only when enabled
- Fix chat input drag-and-drop for files from Explorer (path references and images)
- Improve dependency detection and permission approvals`,
      zh: `- 新增「调试日志」开关（默认关闭），仅开启时显示 Webview 开发者工具按钮
- 修复输入框拖放：支持从资源管理器拖入文件路径引用与图片
- 改进依赖检测与权限审批`,
    },
  },
  {
    version: '0.0.1',
    date: '2026-08-04',
    content: {
      en: `- Migrate JetBrains CC GUI to VS Code`,
      zh: `- 迁移 JetBrains CC GUI 到 VSCode`,
    },
  },
];
